In [1]:
import json
import requests
import pandas as pd

'''
    Tools
'''
def prettify(obj):
    return json.dumps(obj, indent=2)

def pf(obj): return prettify(obj)

def ppf(obj): print(pf(obj))

resp = requests.post("https://f29bio.northeurope.cloudapp.azure.com/api/Phen2Gene/calc?weightModel=sk&rows=2", json=['HP:0000008', 'HP:0000010'])
ppf(resp.json())

{
  "query": {
    "HP:0000008": {
      "id": "HP:0000008",
      "status": "ok",
      "target": [
        "HP:0000008"
      ]
    },
    "HP:0000010": {
      "id": "HP:0000010",
      "status": "ok",
      "target": [
        "HP:0000010"
      ]
    }
  },
  "response": {
    "HPSE2": {
      "rank": 1,
      "id": 60495,
      "score": 1.0,
      "status": "SeedGene"
    },
    "HOXA13": {
      "rank": 2,
      "id": 3209,
      "score": 0.8727,
      "status": "SeedGene"
    }
  }
}

In [16]:
# ! wget -q https://github.com/foundation29org/PublicCases/blob/master/cipriani_2020/cases.tsv -P _data/.
! wget -q https://raw.githubusercontent.com/foundation29org/PublicCases/master/cipriani_2020/cases.tsv -P _data/.

In [17]:
df = pd.read_csv('_data/cases.tsv', sep='\t')
df.head()

,Patient_identifier,Clinical_diagnosis_label,Gene,Genotype,Variant_1,Variant_2,Unnamed: 6
0,P1,"HP:0011516, HP:0008275",CNGB3,HOM,c.1810C>T:p.(Arg604*),NaN,NaN
1,P2,"HP:0011516, HP:0008275",CNGB3,HOM,c.1148del:p.(Thr383Ilefs*13),NaN,NaN
2,P3,"HP:0011516, HP:0008275",ATF6,HOM,c.970C>T:p.(Arg324Cys),NaN,NaN
3,P4,"HP:0011516, HP:0008275",POC1B,HOM,c.130_138del:p.(Ile44_Leu46del),NaN,NaN
4,P5,"HP:0011516, HP:0008275",ATF6,HOM,c.1187+5G>C:p.?,NaN,NaN

In [ ]:
'''
    Datasources
'''    
class DataSource():
    def __init__(self, df):
        self.rows =self._load_rows(df)
        
    def ._load_rows(self, df)